/* Mobile-first procedural airport renderer. */
window.Airport3D=(()=>{let renderer,scene,camera,root,airportRoot,ground;const flights=new Map(),vehicles=new Map();const THREE_URL='https://unpkg.com/three@0.160.0/build/three.min.js';const loadThree=()=>new Promise((res,rej)=>{if(window.THREE)return res(window.THREE);const s=document.createElement('script');s.src=THREE_URL;s.onload=()=>res(window.THREE);s.onerror=rej;document.head.appendChild(s)});const mat=(c,r=.82)=>new THREE.MeshStandardMaterial({color:c,roughness:r});const box=(w,h,d,m)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);const line=(a,b,m,w)=>{const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a[0],.06,a[1]),new THREE.Vector3(b[0],.06,b[1])]);const o=new THREE.Line(g,m);o.scale.y=w||1;return o};function path(points,width,color,center=false){if(!points||points.length<2)return;const m=mat(color);for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);const p=new THREE.Mesh(new THREE.PlaneGeometry(width,len),m);p.rotation.x=-Math.PI/2;p.rotation.z=-Math.atan2(dz,dx);p.position.set((a[0]+b[0])/2,.025,(a[1]+b[1])/2);airportRoot.add(p);if(center){const cm=new THREE.LineBasicMaterial({color:0xf5f5f5});airportRoot.add(line(a,b,cm,1))}}}
function terminal(points){if(!points?.length)return;const xs=points.map(p=>p[0]),zs=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),b=box(Math.max(20,maxX-minX),14,Math.max(12,maxZ-minZ),mat(0x737d86));b.position.set((minX+maxX)/2,7,(minZ+maxZ)/2);airportRoot.add(b);for(let x=minX+6;x<maxX;x+=10){const g=box(5,3,.35,mat(0x78b8d8));g.position.set(x,7,minZ-.3);airportRoot.add(g)}}
function stand(x,z,name){const c=new THREE.Mesh(new THREE.CylinderGeometry(12,12,.18,24),mat(0x34383c));c.position.set(x,.12,z);airportRoot.add(c);const ring=new THREE.Mesh(new THREE.RingGeometry(10.8,11.2,24),new THREE.MeshBasicMaterial({color:0xf2f2f2,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.23,z);airportRoot.add(ring);if(name){const div=document.createElement('div');div.className='mapOverlay';div.textContent=name;div.style.display='none'}}
function aircraft(code){const g=new THREE.Group(),body=mat(0xe9edf0),dark=mat(0x263238),wing=mat(0xc8ced4),glass=mat(0x23465c);const f=new THREE.Mesh(new THREE.CylinderGeometry(2.15,2.15,24,18),body);f.rotation.z=Math.PI/2;g.add(f);const w=box(13,.5,3.5,wing);w.position.y=-.2;g.add(w);const t=box(3,3.8,1.4,dark);t.position.set(-10,2.4,0);g.add(t);const cockpit=box(2,.7,3.8,glass);cockpit.position.set(9,1,0);g.add(cockpit);[-5,5].forEach(x=>{const e=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,3.2,12),dark);e.rotation.z=Math.PI/2;e.position.set(x,-1,0);g.add(e)});if(code==='A388')g.scale.set(1.8,1.35,1.35);else if(code==='B77W'||code==='A359')g.scale.set(1.35,1.1,1.1);else if(code==='A321')g.scale.set(1.08,1,1);return g}
function vehicle(type){const g=new THREE.Group(),colors={fuel:0xd88922,baggage:0x688ed0,catering:0xd9d9d9,pushback:0xe6a62b,tug:0xe6a62b};const b=box(7,2.6,4,mat(colors[type]||0xe6a62b));b.position.y=2;g.add(b);const cab=box(2.5,2.1,3,mat(0x263238));cab.position.set(2.1,3.4,0);g.add(cab);return g}
function clearAirport(){if(airportRoot){scene.remove(airportRoot);airportRoot=null}flights.clear();vehicles.forEach(v=>scene.remove(v.mesh));vehicles.clear()}
function setup(c){scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb6d8);scene.add(new THREE.HemisphereLight(0xffffff,0x53616b,2));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(100,180,80);scene.add(sun);root=new THREE.Group();scene.add(root);ground=new THREE.Mesh(new THREE.PlaneGeometry(1800,1800),mat(0x52684f));ground.rotation.x=-Math.PI/2;ground.position.y=-.03;root.add(ground);airportRoot=new THREE.Group();root.add(airportRoot);camera=new THREE.PerspectiveCamera(48,c.clientWidth/c.clientHeight,.1,5000);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(c.clientWidth,c.clientHeight);c.innerHTML='';c.appendChild(renderer.domElement);let drag=false,lx=0,ly=0,dist=410,az=0,el=.62;const cam=()=>{camera.position.set(Math.sin(az)*dist*Math.cos(el),Math.sin(el)*dist,Math.cos(az)*dist*Math.cos(el));camera.lookAt(0,0,0)};c.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;az-=(e.clientX-lx)*.008;el=Math.max(.18,Math.min(1.35,el+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;cam()});['pointerup','pointercancel'].forEach(x=>c.addEventListener(x,()=>drag=false));c.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(80,Math.min(900,dist+e.deltaY*.35));cam()},{passive:false});const resize=()=>{camera.aspect=c.clientWidth/c.clientHeight;camera.updateProjectionMatrix();renderer.setSize(c.clientWidth,c.clientHeight)};window.addEventListener('resize',resize);cam();const loop=()=>{requestAnimationFrame(loop);flights.forEach(o=>{o.mesh.position.lerp(o.target,.055);if(o.mesh.position.y>10)o.mesh.rotation.y+=.012});vehicles.forEach(v=>v.mesh.position.lerp(v.target,.075));renderer.render(scene,camera)};loop()}
async function init(c){try{await loadThree();setup(c);return true}catch(e){c.innerHTML='<div class="mapOverlay">3D scene unavailable.</div>';return false}}
function renderAirport(a,geometry=[]){if(!airportRoot)return;clearAirport();airportRoot=new THREE.Group();root.add(airportRoot);const lat=a.latitude||0,lon=a.longitude||0,scale=90000,xy=p=>[(p[1]-lon)*scale,-(p[0]-lat)*scale];let count=0;geometry.slice(0,500).forEach(g=>{const pts=(g.points||[]).map(xy);if(g.type==='runway'){path(pts,Math.max(35,Math.min(80,(Math.hypot(pts.at(-1)[0]-pts[0][0],pts.at(-1)[1]-pts[0][1]))*.08)),0x292c2f,true);count++}else if(g.type==='taxiway'){path(pts,18,0x3b3d40,true);count++}else if(g.type==='terminal'){terminal(pts);count++}else if(g.type==='gate'&&g.point){const p=xy(g.point);stand(p[0],p[1],g.name);count++}});if(!count){path([[-180,0],[180,0]],45,0x292c2f,true);path([[-80,35],[80,35]],18,0x3b3d40,true);terminal([[-55,48],[55,48],[55,75],[-55,75]]);for(let x=-45;x<=45;x+=18)stand(x,25,'A'+(Math.round((x+45)/18)+1))}}
function addFlight(f){if(!airportRoot||flights.has(f.id))return;const m=aircraft(f.code);m.position.set(-180+(flights.size%4)*45,4,-120-Math.floor(flights.size/4)*30);root.add(m);flights.set(f.id,{mesh:m,target:m.position.clone()});setFlightStatus(f)}
function syncVehicles(f){const o=flights.get(f.id);if(!o)return;['fuel','baggage','catering','pushback'].forEach((type,i)=>{const key=f.id+':'+type;if(type==='pushback'&&f.status!=='pushback')return;if(f.services?.[type]===true){const v=vehicles.get(key);if(v)v.target.set(v.mesh.position.x,0,-250);return}if(!vehicles.has(key)){const m=vehicle(type);root.add(m);m.position.set(-100+i*20,1,-70);vehicles.set(key,{mesh:m,target:m.position.clone()})}const v=vehicles.get(key),p=o.mesh.position;v.target.set(p.x+(i-1.5)*9,1,p.z+13)})}
function setFlightStatus(f){const o=flights.get(f.id);if(!o)return;const t={arriving:[0,4,-180],parked:[0,4,25],servicing:[0,4,25],boarding:[0,4,25],ready:[0,4,25],pushback:[0,4,65],taxiing:[120,4,65],departed:[240,35,65]},p=t[f.status]||t.parked;o.target.set(...p);syncVehicles(f);if(f.status==='taxiing')o.mesh.rotation.y=.7;if(f.status==='departed')setTimeout(()=>{const x=flights.get(f.id);if(x){root.remove(x.mesh);flights.delete(f.id)}},1300)}
function sync(list){const ids=new Set(list.map(f=>f.id));flights.forEach((o,id)=>{if(!ids.has(id)){root.remove(o.mesh);flights.delete(id)}});list.forEach(f=>{if(!flights.has(f.id))addFlight(f);setFlightStatus(f)})}
return{init,renderAirport,sync,addFlight,setFlightStatus};})();
