/* Airport Manager airport renderer: accurate segmented taxiways, aprons and airport detail. */
window.Airport3D=(()=>{let renderer,scene,camera,root,airportRoot;const flights=new Map(),vehicles=new Map();const THREE_URL='https://unpkg.com/three@0.160.0/build/three.min.js';const loadThree=()=>new Promise((res,rej)=>{if(window.THREE)return res(window.THREE);const s=document.createElement('script');s.src=THREE_URL;s.onload=()=>res(window.THREE);s.onerror=rej;document.head.appendChild(s)});const mat=(c,r=.82)=>new THREE.MeshStandardMaterial({color:c,roughness:r});const box=(w,h,d,m)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);
function seg(a,b,w,c,y=.035){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.5)return;const o=box(w,.08,len,mat(c));o.position.set((a[0]+b[0])/2,y,(a[1]+b[1])/2);o.rotation.y=Math.atan2(dx,dz);airportRoot.add(o)}
function mark(a,b,w,c,y=.1){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<1)return;const o=box(w,.025,len,mat(c));o.position.set((a[0]+b[0])/2,y,(a[1]+b[1])/2);o.rotation.y=Math.atan2(dx,dz);airportRoot.add(o)}
function path(p,w,c,center=false){if(!p||p.length<2)return;for(let i=1;i<p.length;i++){seg(p[i-1],p[i],w,c);if(center)mark(p[i-1],p[i],.65,0xf4c542,.1)}}
function runway(p){if(!p||p.length<2)return;const a=p[0],b=p.at(-1),len=Math.hypot(b[0]-a[0],b[1]-a[1]),w=Math.max(40,Math.min(80,len*.075));path(p,w,0x292c2f);const dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz),nx=-dz/l,nz=dx/l;for(let i=1;i<9;i++){const t=i/9,x=a[0]+(b[0]-a[0])*t,z=a[1]+(b[1]-a[1])*t;mark([x+nx*10,z+nz*10],[x-nx*10,z-nz*10],2,0xffffff)}}
function apron(p){if(!p||p.length<3)return;const xs=p.map(x=>x[0]),zs=p.map(x=>x[1]);const o=box(Math.max(40,Math.max(...xs)-Math.min(...xs)),.12,Math.max(35,Math.max(...zs)-Math.min(...zs)),mat(0x55595c));o.position.set((Math.min(...xs)+Math.max(...xs))/2,.015,(Math.min(...zs)+Math.max(...zs))/2);airportRoot.add(o)}
function terminal(p){if(!p?.length)return;const xs=p.map(x=>x[0]),zs=p.map(x=>x[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),w=Math.max(30,maxX-minX),d=Math.max(16,maxZ-minZ);const b=box(w,14,d,mat(0x6f7982));b.position.set((minX+maxX)/2,7,(minZ+maxZ)/2);airportRoot.add(b);const roof=box(w*.94,1.2,d*.94,mat(0x30363b));roof.position.set((minX+maxX)/2,14.5,(minZ+maxZ)/2);airportRoot.add(roof);for(let x=minX+6;x<maxX-2;x+=9){const g=box(5,3,.35,mat(0x75b9d7));g.position.set(x,7,minZ-.35);airportRoot.add(g)}}
function hangar(x,z,w=34,d=24){const b=box(w,13,d,mat(0x59636a));b.position.set(x,6.5,z);airportRoot.add(b);const roof=box(w*.94,1,d*.94,mat(0x30363b));roof.position.set(x,13.5,z);airportRoot.add(roof);const door=box(w*.68,7,.5,mat(0x78a8bc));door.position.set(x,4,z-d/2-.2);airportRoot.add(door)}
function tower(x,z){const b=box(7,16,7,mat(0x707981));b.position.set(x,8,z);airportRoot.add(b);const cab=box(11,3,11,mat(0x27343b));cab.position.set(x,17,z);airportRoot.add(cab);const top=box(6,3,6,mat(0x7db4c9));top.position.set(x,20,z);airportRoot.add(top)}
function stand(x,z,name){const c=new THREE.Mesh(new THREE.CylinderGeometry(13,13,.22,32),mat(0x373b3e));c.position.set(x,.13,z);airportRoot.add(c);const r=new THREE.Mesh(new THREE.RingGeometry(11.1,11.7,32),new THREE.MeshBasicMaterial({color:0xf2f2f2,side:THREE.DoubleSide}));r.rotation.x=-Math.PI/2;r.position.set(x,.25,z);airportRoot.add(r);const lead=box(1,.08,18,mat(0xf2f2f2));lead.position.set(x,.28,z+18);airportRoot.add(lead);if(name){const label=box(5,.12,1.2,mat(0xffc400));label.position.set(x+15,.3,z);airportRoot.add(label)}}
function hold(x,z,ang){for(let i=-3;i<=3;i++){const o=box(.55,.05,7,mat(0xffffff));o.position.set(x+i*2,z,.16);o.rotation.y=ang;airportRoot.add(o)}}
function aircraft(code){const g=new THREE.Group(),body=mat(0xe9edf0),dark=mat(0x263238),wing=mat(0xc8ced4),glass=mat(0x23465c);const f=new THREE.Mesh(new THREE.CylinderGeometry(2.15,2.15,24,18),body);f.rotation.z=Math.PI/2;g.add(f);const w=box(13,.5,3.5,wing);w.position.y=-.2;g.add(w);const t=box(3,3.8,1.4,dark);t.position.set(-10,2.4,0);g.add(t);const c=box(2,.7,3.8,glass);c.position.set(9,1,0);g.add(c);[-5,5].forEach(x=>{const e=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,3.2,12),dark);e.rotation.z=Math.PI/2;e.position.set(x,-1,0);g.add(e)});if(code==='A388')g.scale.set(1.8,1.35,1.35);else if(code==='B77W'||code==='A359')g.scale.set(1.35,1.1,1.1);else if(code==='A321')g.scale.set(1.08,1,1);return g}
function vehicle(type){const colors={fuel:0xd88922,baggage:0x688ed0,catering:0xd9d9d9,pushback:0xe6a62b,tug:0xe6a62b},g=new THREE.Group();const b=box(7,2.6,4,mat(colors[type]||0xe6a62b));b.position.y=2;g.add(b);const cab=box(2.5,2.1,3,mat(0x263238));cab.position.set(2.1,3.4,0);g.add(cab);return g}
function clearAirport(){flights.forEach(o=>root.remove(o.mesh));flights.clear();vehicles.forEach(v=>root.remove(v.mesh));vehicles.clear();if(airportRoot)root.remove(airportRoot);airportRoot=new THREE.Group();root.add(airportRoot)}
function setup(c){scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb6d8);scene.add(new THREE.HemisphereLight(0xffffff,0x53616b,2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(120,180,80);scene.add(sun);root=new THREE.Group();scene.add(root);const ground=new THREE.Mesh(new THREE.PlaneGeometry(1800,1800),mat(0x52684f));ground.rotation.x=-Math.PI/2;ground.position.y=-.03;root.add(ground);airportRoot=new THREE.Group();root.add(airportRoot);camera=new THREE.PerspectiveCamera(48,c.clientWidth/c.clientHeight,.1,5000);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(c.clientWidth,c.clientHeight);c.innerHTML='';c.appendChild(renderer.domElement);let drag=false,lx=0,ly=0,dist=410,az=0,el=.62;const cam=()=>{camera.position.set(Math.sin(az)*dist*Math.cos(el),Math.sin(el)*dist,Math.cos(az)*dist*Math.cos(el));camera.lookAt(0,0,0)};c.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;az-=(e.clientX-lx)*.008;el=Math.max(.18,Math.min(1.35,el+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;cam()});['pointerup','pointercancel'].forEach(x=>c.addEventListener(x,()=>drag=false));c.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(80,Math.min(900,dist+e.deltaY*.35));cam()},{passive:false});const resize=()=>{camera.aspect=c.clientWidth/c.clientHeight;camera.updateProjectionMatrix();renderer.setSize(c.clientWidth,c.clientHeight)};window.addEventListener('resize',resize);cam();const loop=()=>{requestAnimationFrame(loop);flights.forEach(o=>{o.mesh.position.lerp(o.target,.055);if(o.mesh.position.y>10)o.mesh.rotation.y+=.012});vehicles.forEach(v=>v.mesh.position.lerp(v.target,.075));renderer.render(scene,camera)};loop()}
async function init(c){try{await loadThree();setup(c);return true}catch(e){c.innerHTML='<div class="mapOverlay">3D scene unavailable.</div>';return false}}
function renderAirport(a,geometry=[]){if(!airportRoot)return;clearAirport();const lat=a.latitude||0,lon=a.longitude||0,scale=90000,xy=p=>[(p[1]-lon)*scale,-(p[0]-lat)*scale];const usable=geometry.filter(g=>g.type==='runway'||g.type==='taxiway'||g.type==='terminal'||g.type==='gate').slice(0,700);let runways=0,taxis=0,terms=0,gates=0;usable.forEach(g=>{const pts=(g.points||[]).map(xy).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));if(g.type==='runway'){runway(pts);runways++}else if(g.type==='taxiway'){path(pts,20,0x3b3d40,true);taxis++}else if(g.type==='terminal'){terminal(pts);terms++}else if(g.type==='gate'&&g.point){const p=xy(g.point);stand(p[0],p[1],g.name);gates++}});if(!runways){runway([[-220,0],[220,0]]);runway([[-220,95],[220,95]])}if(!taxis){path([[-220,0],[-165,0],[-120,30],[-80,55],[80,55],[120,30],[165,0],[220,0]],20,0x3b3d40,true);path([[-165,95],[-120,70],[-80,55]],18,0x3b3d40,true)}if(!terms)terminal([[-75,62],[75,62],[75,88],[-75,88]]);if(!gates)for(let x=-60;x<=60;x+=20)stand(x,42,'A'+(Math.round((x+60)/20)+1));apron([[-115,35],[115,35],[115,95],[-115,95]]);hangar(-125,125);hangar(125,125);tower(105,78);hold(-165,0,Math.PI/2)}
function addFlight(f){if(!airportRoot||flights.has(f.id))return;const m=aircraft(f.code);m.position.set(-180+(flights.size%4)*45,4,-120-Math.floor(flights.size/4)*30);airportRoot.add(m);flights.set(f.id,{mesh:m,target:m.position.clone()});setFlightStatus(f)}
function syncVehicles(f){const o=flights.get(f.id);if(!o)return;['fuel','baggage','catering','pushback'].forEach((type,i)=>{const key=f.id+':'+type;if(type==='pushback'&&f.status!=='pushback')return;if(f.services?.[type]===true){const v=vehicles.get(key);if(v)v.target.set(v.mesh.position.x,0,-250);return}if(!vehicles.has(key)){const m=vehicle(type);airportRoot.add(m);m.position.set(-100+i*20,1,-70);vehicles.set(key,{mesh:m,target:m.position.clone()})}const v=vehicles.get(key),p=o.mesh.position;v.target.set(p.x+(i-1.5)*9,1,p.z+13)})}
function setFlightStatus(f){const o=flights.get(f.id);if(!o)return;const t={arriving:[0,4,-180],parked:[0,4,25],servicing:[0,4,25],boarding:[0,4,25],ready:[0,4,25],pushback:[0,4,65],taxiing:[120,4,65],departed:[240,35,65]},p=t[f.status]||t.parked;o.target.set(...p);syncVehicles(f);if(f.status==='taxiing')o.mesh.rotation.y=.7;if(f.status==='departed')setTimeout(()=>{const x=flights.get(f.id);if(x){airportRoot.remove(x.mesh);flights.delete(f.id)}},1300)}
function sync(list){const ids=new Set(list.map(f=>f.id));flights.forEach((o,id)=>{if(!ids.has(id)){airportRoot.remove(o.mesh);flights.delete(id)}});list.forEach(f=>{if(!flights.has(f.id))addFlight(f);setFlightStatus(f)})}
return{init,renderAirport,sync,addFlight,setFlightStatus};})();