const db=window.airportManagerSupabase;
const Game=window.AirportManagerGame;
const SAVE_KEY='airport-manager-save-v3';
let airports=[],selectedAirport=null,state=loadState(),airportMap=null,airportLayers=[];
const list=document.getElementById('airportList'),msg=document.getElementById('message');
function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=JSON.parse(raw),f=Game.newState();return{...f,...s,vehicles:{...f.vehicles,...s.vehicles},staff:{...f.staff,...s.staff},stats:{...f.stats,...s.stats},flights:Array.isArray(s.flights)?s.flights:[],events:Array.isArray(s.events)?s.events:[],ownedAirports:Array.isArray(s.ownedAirports)?s.ownedAirports:[],contracts:Array.isArray(s.contracts)?s.contracts:[]}}}catch(e){console.warn(e)}return Game.newState()}
function saveState(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(e){console.warn('Save failed',e)}}
function money(){return state.unlimited?'∞':`$${Math.round(state.money).toLocaleString()}`}
function update(){document.getElementById('money').textContent=`💰 ${money()}`;document.getElementById('level').textContent=`⭐ Level ${state.level}`;document.getElementById('reputation').textContent=`🏆 Rep ${state.reputation}`;document.getElementById('vehicles').textContent=state.unlimited?'∞':Object.values(state.vehicles).reduce((a,b)=>a+b,0);document.getElementById('atc').textContent=state.unlimited?'∞':state.staff.atc||0;document.getElementById('aircraft').textContent=state.stats.aircraft;document.getElementById('passengers').textContent=state.stats.passengers.toLocaleString();document.getElementById('finance').innerHTML=`Revenue <b>$${state.stats.revenue.toLocaleString()}</b><br>Expenses <b>$${state.stats.expenses.toLocaleString()}</b><br>Completed <b>${state.stats.completed}</b><br>Delayed <b>${state.stats.delayed}</b>`;document.getElementById('events').innerHTML=state.events.length?state.events.slice(0,8).map(e=>`<div class="event"><b>${e.title}</b><br><small>${e.description}</small></div>`).join(''):'No events yet.';renderFlights();renderContracts();saveState()}
function render(items=airports){list.innerHTML=items.length?items.map(a=>`<div class="airport ${selectedAirport?.icao===a.icao?'active':''}" data-icao="${a.icao}"><b>${a.icao}</b> · ${a.name}<small>${a.city||''}${a.country?', '+a.country:''}</small></div>`).join(''):'<p>No airports found.</p>';list.querySelectorAll('.airport').forEach(e=>e.onclick=()=>selectAirport(e.dataset.icao))}
function initMap(a){if(!airportMap)airportMap=L.map('map',{zoomControl:true,preferCanvas:true});airportMap.setView([a.latitude,a.longitude],14);airportLayers.forEach(x=>airportMap.removeLayer(x));airportLayers=[];airportLayers.push(L.tileLayer('https://global.imagery.hotosm.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenAerialMap / HOT'}).addTo(airportMap));airportLayers.push(L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{opacity:.18,maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(airportMap))}
async function loadOSM(a){const q=`[out:json][timeout:25];(way["aeroway"~"^(runway|taxiway|taxilane)$"](around:8000,${a.latitude},${a.longitude});way["aeroway"="terminal"](around:8000,${a.latitude},${a.longitude});node["aeroway"~"^(gate|parking_position)$"](around:8000,${a.latitude},${a.longitude}););out body geom;`;try{const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));if(!r.ok)throw Error(r.status);const d=await r.json();d.elements.forEach(el=>{const t=el.tags||{};if(el.type==='way'&&el.geometry?.length){const p=el.geometry.map(x=>[x.lat,x.lon]);let l=t.aeroway==='runway'?L.polyline(p,{weight:10,opacity:.9}).bindTooltip(t.ref||'Runway'):t.aeroway==='terminal'?L.polygon(p,{fillOpacity:.25,weight:2}).bindTooltip(t.name||'Terminal'):L.polyline(p,{weight:4,opacity:.65}).bindTooltip(t.ref||t.name||'Taxiway');l.addTo(airportMap);airportLayers.push(l)}else if(el.type==='node'&&el.lat&&el.lon){const l=L.circleMarker([el.lat,el.lon],{radius:4}).bindTooltip(t.ref||t.name||'Stand');l.addTo(airportMap);airportLayers.push(l)}});msg.textContent=`${a.name} loaded with live airport geometry.`}catch(e){msg.textContent=`${a.name} loaded. Live geometry temporarily unavailable.`;console.warn(e)}}
async function selectAirport(icao){const a=airports.find(x=>x.icao===icao);if(!a)return;selectedAirport=a;document.getElementById('airportName').textContent=a.name;document.getElementById('airportCode').textContent=`${a.icao} · ${a.city||''}${a.country?', '+a.country:''}`;render();if(!airportMap)initMap(a);else airportMap.setView([a.latitude,a.longitude],14);await loadOSM(a)}
async function loadAirports(){msg.textContent='Loading airport network...';const{data,error}=await db.from('airports').select('*').order('icao');if(error){msg.textContent=`Database error: ${error.message}`;return}airports=data||[];render();update();if(airports.length)selectAirport(airports[0].icao)}
function addFlight(){const code=document.getElementById('aircraftType').value,num=document.getElementById('flightNumber').value.trim()||'FLIGHT';const r=Game.schedule(state,code,num,'A1');if(!r[0]){msg.textContent=r[1];return}Game.GameEvent(state,'Flight accepted',`${num} ${code} entered the turnaround queue.`);msg.textContent=`${num} accepted. Complete its services before dispatch.`;update()}
function serviceFlight(id){const r=Game.service(state,id);msg.textContent=r[1];update()}
function dispatchFlight(id){const r=Game.dispatch(state,id);msg.textContent=r[1];if(r[0])Game.GameEvent(state,'ATC clearance',`${id} cleared for departure.`);update()}
function simulateStep(){const before=state.stats.completed;Game.tick(state);if(state.stats.completed>before)Game.recordContractProgress(state);}
function advanceSim(){if(!state.flights.some(f=>f.status!=='departed')){msg.textContent='No active flights.';return}simulateStep();msg.textContent='Simulation advanced 10%. Automatic operations continue every 5 seconds.';update()}
function buyVehicleType(t){const r=Game.buy(state,t);msg.textContent=r[1];if(r[0])Game.GameEvent(state,'Vehicle purchased',`${t} equipment added.`);update()}
function hireRole(r){const x=Game.hire(state,r);msg.textContent=x[1];if(x[0])Game.GameEvent(state,'Staff hired',`${r} staff added.`);update()}
function renderFlights(){const q=document.getElementById('flightQueue');q.innerHTML=state.flights.length?state.flights.map(f=>{const services=Object.entries(f.services||{}).map(([k,v])=>`${v?'✓':'○'} ${k}`).join(' · ');return`<div class="flightRow"><div><b>${f.flightNumber}</b> · ${f.code}<span>${f.status} · ${f.progress}%</span></div><small>${services}</small><div><button onclick="serviceFlight('${f.id}')">Service next</button><button onclick="dispatchFlight('${f.id}')">ATC dispatch</button></div></div>`}).join(''):'No active turnarounds.'}
function renderContracts(){const el=document.getElementById('contracts');if(!el)return;el.innerHTML=state.contracts.length?state.contracts.map(c=>`<div class="event"><b>${c.name}</b><br>${c.completed?'✅ Complete':`Progress ${c.progress}/${c.target}`} · $${c.payout.toLocaleString()}</div>`).join(''):'No contracts yet.'}
function newContract(){const names=['Regional turnaround contract','International hub contract','Cargo handling contract'];const n=names[state.contracts.length%names.length];Game.acceptContract(state,n,25000+state.contracts.length*10000,5+state.contracts.length*2);msg.textContent=`Contract accepted: ${n}.`;update()}
function buyAirport(){if(!selectedAirport){msg.textContent='Select an airport first.';return}const r=Game.purchaseAirport(state,selectedAirport.icao);msg.textContent=r[0]?`${selectedAirport.icao} acquired for $${r[1].toLocaleString()}.`:`${typeof r[1]==='number'?'Airport costs $'+r[1].toLocaleString():r[1]}`;update()}
function redeemCode(){const i=document.getElementById('storeCode'),c=i.value.trim();if(c==='123123'){Game.activateUnlimited(state);i.value='';msg.textContent='Developer code accepted: unlimited money and resources activated.';update()}else msg.textContent='Invalid code'}
document.getElementById('expandBtn').onclick=()=>{const r=Game.expand(state);msg.textContent=r[0]?`Airport expanded for $${r[1].toLocaleString()}.`:`Expansion costs $${r[1].toLocaleString()}.`;update()};document.getElementById('search').oninput=e=>{const q=e.target.value.toLowerCase();render(airports.filter(a=>`${a.icao} ${a.name} ${a.city||''} ${a.country||''}`.toLowerCase().includes(q)))};update();loadAirports();setInterval(()=>{if(state.flights.some(f=>f.status!=='departed')){simulateStep();update()}},5000);window.addEventListener('beforeunload',saveState);
