const db=window.airportManagerSupabase;const Game=window.AirportManagerGame;const SAVE_KEY='airport-manager-save-v4',GEOM_KEY='airport-manager-geometry-v1';let airports=[],selectedAirport=null,state=loadState(),threeReady=false;const list=document.getElementById('airportList'),msg=document.getElementById('message');
function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=JSON.parse(raw),f=Game.newState();return{...f,...s,vehicles:{...f.vehicles,...s.vehicles},staff:{...f.staff,...s.staff},stats:{...f.stats,...s.stats},flights:Array.isArray(s.flights)?s.flights:[],events:Array.isArray(s.events)?s.events:[],ownedAirports:Array.isArray(s.ownedAirports)?s.ownedAirports:[],contracts:Array.isArray(s.contracts)?s.contracts:[]}}}catch(e){console.warn(e)}return Game.newState()}
function saveState(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(e){console.warn('Save failed',e)}}function money(){return state.unlimited?'∞':`$${Math.round(state.money).toLocaleString()}`}
function update(){document.getElementById('money').textContent=`💰 ${money()}`;document.getElementById('level').textContent=`⭐ Level ${state.level}`;document.getElementById('reputation').textContent=`🏆 Rep ${state.reputation}`;document.getElementById('vehicles').textContent=state.unlimited?'∞':Object.values(state.vehicles).reduce((a,b)=>a+b,0);document.getElementById('atc').textContent=state.unlimited?'∞':state.staff.atc||0;document.getElementById('aircraft').textContent=state.stats.aircraft;document.getElementById('passengers').textContent=state.stats.passengers.toLocaleString();document.getElementById('finance').innerHTML=`Revenue <b>$${state.stats.revenue.toLocaleString()}</b><br>Expenses <b>$${state.stats.expenses.toLocaleString()}</b><br>Completed <b>${state.stats.completed}</b><br>Delayed <b>${state.stats.delayed}</b>`;document.getElementById('events').innerHTML=state.events.length?state.events.slice(0,8).map(e=>`<div class="event"><b>${e.title}</b><br><small>${e.description}</small></div>`).join(''):'No events yet.';renderFlights();renderContracts();if(threeReady)Airport3D.sync(state.flights);saveState()}
function render(items=airports){list.innerHTML=items.length?items.map(a=>`<div class="airport ${selectedAirport?.icao===a.icao?'active':''}" data-icao="${a.icao}"><b>${a.icao}</b> · ${a.name}<small>${a.city||''}${a.country?', '+a.country:''}</small></div>`).join(''):'<p>No airports found.</p>';list.querySelectorAll('.airport').forEach(e=>e.onclick=()=>selectAirport(e.dataset.icao))}
function mapGeometry(d){return(d.elements||[]).flatMap(el=>{const t=el.tags||{};if(el.type==='way'&&el.geometry?.length){const type=t.aeroway==='runway'?'runway':t.aeroway==='terminal'?'terminal':(t.aeroway==='taxiway'||t.aeroway==='taxilane')?'taxiway':null;if(!type)return[];const pts=el.geometry.map(x=>[x.lat,x.lon]);return[{type,points:pts,point:pts[Math.floor(pts.length/2)],name:t.name||t.ref||''}]}if(el.type==='node'&&el.lat!=null&&el.lon!=null&&(t.aeroway==='gate'||t.aeroway==='parking_position'))return[{type:'gate',point:[el.lat,el.lon],name:t.ref||t.name||'Stand'}];return[]})}
function runwayGeometry(a,r){const lat=a.latitude||0,lon=a.longitude||0,len=Math.max(300,Number(r.length_m)||3000),heading=(Number(r.heading)||0)*Math.PI/180,dx=Math.sin(heading)*(len/2)/111320,dy=Math.cos(heading)*(len/2)/110540;return{type:'runway',points:[[lat-dy,lon-dx],[lat+dy,lon+dx]],name:r.ident||''}}
async function databaseGeometry(a){try{const{data,error}=await db.from('runways').select('*').eq('airport_id',a.id);if(error)throw error;return(data||[]).map(r=>runwayGeometry(a,r))}catch(e){console.warn('Runway fallback failed',e);return[]}}
function geometryCacheGet(icao){try{const c=JSON.parse(localStorage.getItem(GEOM_KEY)||'{}');return Array.isArray(c[icao])?c[icao]:null}catch(e){return null}}
function geometryCachePut(icao,g){try{const c=JSON.parse(localStorage.getItem(GEOM_KEY)||'{}');c[icao]=g;localStorage.setItem(GEOM_KEY,JSON.stringify(c))}catch(e){}}
async function overpass(a,url){const q=`[out:json][timeout:18];(way["aeroway"~"^(runway|taxiway|taxilane|terminal)$"](around:8000,${a.latitude},${a.longitude});node["aeroway"~"^(gate|parking_position)$"](around:8000,${a.latitude},${a.longitude}););out body geom;`;const r=await fetch(url+'?data='+encodeURIComponent(q));if(!r.ok)throw Error(`${r.status} ${url}`);return mapGeometry(await r.json())}
async function loadOSM(a){const cached=geometryCacheGet(a.icao);if(cached?.length){if(threeReady)Airport3D.renderAirport(a,cached);msg.textContent=`${a.name} loaded from cached airport geometry.`;return}const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const endpoint of endpoints){try{const g=await overpass(a,endpoint);if(g.length){geometryCachePut(a.icao,g);if(threeReady)Airport3D.renderAirport(a,g);msg.textContent=`${a.name} loaded with real OSM airport geometry.`;return}}catch(e){console.warn(e)}}const dbGeom=await databaseGeometry(a);if(threeReady)Airport3D.renderAirport(a,dbGeom);msg.textContent=dbGeom.length?`${a.name} loaded from runway database data.`:`${a.name} loaded with procedural airport layout.`}
async function selectAirport(icao){const a=airports.find(x=>x.icao===icao);if(!a)return;selectedAirport=a;document.getElementById('airportName').textContent=a.name;document.getElementById('airportCode').textContent=`${a.icao} · ${a.city||''}${a.country?', '+a.country:''}`;render();if(threeReady)Airport3D.renderAirport(a,[]);await loadOSM(a);if(threeReady)Airport3D.sync(state.flights)}
async function loadAirports(){msg.textContent='Loading airport network...';const{data,error}=await db.from('airports').select('*').order('icao');if(error){msg.textContent=`Database error: ${error.message}`;return}airports=data||[];render();update();if(airports.length)selectAirport(airports[0].icao)}
function addFlight(){const code=document.getElementById('aircraftType').value,num=document.getElementById('flightNumber').value.trim()||'FLIGHT';const r=Game.schedule(state,code,num,'A1');if(!r[0]){msg.textContent=r[1];return}Game.GameEvent(state,'Flight accepted',`${num} ${code} entered the turnaround queue.`);msg.textContent=`${num} accepted. Aircraft arriving at the airport.`;update()}
function serviceFlight(id){const r=Game.service(state,id);msg.textContent=r[1];update()}function dispatchFlight(id){const r=Game.dispatch(state,id);msg.textContent=r[1];if(r[0])Game.GameEvent(state,'ATC clearance',`${id} cleared for pushback and departure.`);update()}
function simulateStep(){const before=state.stats.completed;Game.tick(state);if(state.stats.completed>before)Game.recordContractProgress(state)}function advanceSim(){if(!state.flights.some(f=>f.status!=='departed')){msg.textContent='No active flights.';return}simulateStep();msg.textContent='Simulation advanced 10%. Automatic operations continue every 5 seconds.';update()}
function buyVehicleType(t){const r=Game.buy(state,t);msg.textContent=r[1];if(r[0])Game.GameEvent(state,'Vehicle purchased',`${t} equipment added.`);update()}function hireRole(r){const x=Game.hire(state,r);msg.textContent=x[1];if(x[0])Game.GameEvent(state,'Staff hired',`${r} staff added.`);update()}
function renderFlights(){const q=document.getElementById('flightQueue');q.innerHTML=state.flights.length?state.flights.map(f=>{const services=Object.entries(f.services||{}).map(([k,v])=>`${v?'✓':'○'} ${k}`).join(' · ');return`<div class="flightRow"><div><b>${f.flightNumber}</b> · ${f.code}<span>${f.status} · ${f.progress}%</span></div><small>${services}</small><div><button onclick="serviceFlight('${f.id}')">Service next</button><button onclick="dispatchFlight('${f.id}')">ATC / Dispatch</button></div></div>`}).join(''):'No active turnarounds.'}
function renderContracts(){const el=document.getElementById('contracts');if(!el)return;el.innerHTML=state.contracts.length?state.contracts.map(c=>`<div class="event"><b>${c.name}</b><br>${c.completed?'✅ Complete':`Progress ${c.progress}/${c.target}`} · $${c.payout.toLocaleString()}</div>`).join(''):'No contracts yet.'}
function newContract(){const names=['Regional turnaround contract','International hub contract','Cargo handling contract'];const n=names[state.contracts.length%names.length];Game.acceptContract(state,n,25000+state.contracts.length*10000,5+state.contracts.length*2);msg.textContent=`Contract accepted: ${n}.`;update()}
function buyAirport(){if(!selectedAirport){msg.textContent='Select an airport first.';return}const r=Game.purchaseAirport(state,selectedAirport.icao);msg.textContent=r[0]?`${selectedAirport.icao} acquired for $${r[1].toLocaleString()}.`:`${typeof r[1]==='number'?'Airport costs $'+r[1].toLocaleString():r[1]}`;update()}
function redeemCode(){const i=document.getElementById('storeCode'),c=i.value.trim();if(c==='123123'){Game.activateUnlimited(state);i.value='';msg.textContent='Developer code accepted: unlimited money and resources activated.';update()}else msg.textContent='Invalid code'}
document.getElementById('expandBtn').onclick=()=>{const r=Game.expand(state);msg.textContent=r[0]?`Airport expanded for $${r[1].toLocaleString()}.`:`Expansion costs $${r[1].toLocaleString()}.`;update()};document.getElementById('search').oninput=e=>{const q=e.target.value.toLowerCase();render(airports.filter(a=>`${a.icao} ${a.name} ${a.city||''} ${a.country||''}`.toLowerCase().includes(q)))};update();Airport3D.init(document.getElementById('map')).then(ok=>{threeReady=ok;if(selectedAirport){Airport3D.renderAirport(selectedAirport,[]);Airport3D.sync(state.flights);loadOSM(selectedAirport)}});loadAirports();setInterval(()=>{if(state.flights.some(f=>f.status!=='departed')){simulateStep();update()}},5000);window.addEventListener('beforeunload',saveState);