const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync('game-system.js','utf8');
const context={window:{},crypto:{randomUUID:()=>`test-${Date.now()}`},console};
vm.createContext(context);vm.runInContext(code,context);
const Game=context.window.AirportManagerGame;
assert(Game,'game module must load');
let s=Game.newState();
assert.equal(s.money,250000);
assert.equal(Game.buy(s,'fuel')[0],true);
assert.equal(Game.hire(s,'atc')[0],true);
let r=Game.schedule(s,'B738','TEST1','A1');
assert.equal(r[0],true);
const f=r[1];
for(let i=0;i<2;i++)Game.tick(s);
assert(['parked','servicing'].includes(f.status));
for(let i=0;i<4;i++)Game.service(s,f.id);
assert.equal(Object.values(f.services).every(Boolean),true);
assert.equal(Game.dispatch(s,f.id)[0],true);
for(let i=0;i<2;i++)Game.tick(s);
assert(['pushback','taxiing','departed'].includes(f.status));
while(f.status!=='departed')Game.tick(s);
assert.equal(s.stats.completed,1);
assert(s.stats.revenue>0);
Game.acceptContract(s,'Test contract',1000,1);
Game.recordContractProgress(s);
assert.equal(s.contracts[0].completed,true);
Game.activateUnlimited(s);
assert.equal(s.unlimited,true);
assert.equal(s.level,999);
console.log('Airport Manager game-system smoke tests passed');
